// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.29.5
// source: manager.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ManagerAgent_Channel_FullMethodName      = "/bpm.v1.ManagerAgent/Channel"
	ManagerAgent_DownloadFile_FullMethodName = "/bpm.v1.ManagerAgent/DownloadFile"
	ManagerAgent_UploadFile_FullMethodName   = "/bpm.v1.ManagerAgent/UploadFile"
)

// ManagerAgentClient is the client API for ManagerAgent service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ManagerAgent is the single gRPC service exposed by the leader. Agents open
// the bidirectional Channel stream on startup and keep it open for the
// lifetime of the process. Large byte payloads (file download/upload) use
// dedicated streaming RPCs so they don't block the control channel.
type ManagerAgentClient interface {
	Channel(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AgentMessage, LeaderMessage], error)
	DownloadFile(ctx context.Context, in *DownloadRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[FileChunk], error)
	UploadFile(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[UploadChunk, UploadResult], error)
}

type managerAgentClient struct {
	cc grpc.ClientConnInterface
}

func NewManagerAgentClient(cc grpc.ClientConnInterface) ManagerAgentClient {
	return &managerAgentClient{cc}
}

func (c *managerAgentClient) Channel(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AgentMessage, LeaderMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ManagerAgent_ServiceDesc.Streams[0], ManagerAgent_Channel_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AgentMessage, LeaderMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ManagerAgent_ChannelClient = grpc.BidiStreamingClient[AgentMessage, LeaderMessage]

func (c *managerAgentClient) DownloadFile(ctx context.Context, in *DownloadRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[FileChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ManagerAgent_ServiceDesc.Streams[1], ManagerAgent_DownloadFile_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[DownloadRequest, FileChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ManagerAgent_DownloadFileClient = grpc.ServerStreamingClient[FileChunk]

func (c *managerAgentClient) UploadFile(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[UploadChunk, UploadResult], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ManagerAgent_ServiceDesc.Streams[2], ManagerAgent_UploadFile_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[UploadChunk, UploadResult]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ManagerAgent_UploadFileClient = grpc.ClientStreamingClient[UploadChunk, UploadResult]

// ManagerAgentServer is the server API for ManagerAgent service.
// All implementations must embed UnimplementedManagerAgentServer
// for forward compatibility.
//
// ManagerAgent is the single gRPC service exposed by the leader. Agents open
// the bidirectional Channel stream on startup and keep it open for the
// lifetime of the process. Large byte payloads (file download/upload) use
// dedicated streaming RPCs so they don't block the control channel.
type ManagerAgentServer interface {
	Channel(grpc.BidiStreamingServer[AgentMessage, LeaderMessage]) error
	DownloadFile(*DownloadRequest, grpc.ServerStreamingServer[FileChunk]) error
	UploadFile(grpc.ClientStreamingServer[UploadChunk, UploadResult]) error
	mustEmbedUnimplementedManagerAgentServer()
}

// UnimplementedManagerAgentServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedManagerAgentServer struct{}

func (UnimplementedManagerAgentServer) Channel(grpc.BidiStreamingServer[AgentMessage, LeaderMessage]) error {
	return status.Error(codes.Unimplemented, "method Channel not implemented")
}
func (UnimplementedManagerAgentServer) DownloadFile(*DownloadRequest, grpc.ServerStreamingServer[FileChunk]) error {
	return status.Error(codes.Unimplemented, "method DownloadFile not implemented")
}
func (UnimplementedManagerAgentServer) UploadFile(grpc.ClientStreamingServer[UploadChunk, UploadResult]) error {
	return status.Error(codes.Unimplemented, "method UploadFile not implemented")
}
func (UnimplementedManagerAgentServer) mustEmbedUnimplementedManagerAgentServer() {}
func (UnimplementedManagerAgentServer) testEmbeddedByValue()                      {}

// UnsafeManagerAgentServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ManagerAgentServer will
// result in compilation errors.
type UnsafeManagerAgentServer interface {
	mustEmbedUnimplementedManagerAgentServer()
}

func RegisterManagerAgentServer(s grpc.ServiceRegistrar, srv ManagerAgentServer) {
	// If the following call panics, it indicates UnimplementedManagerAgentServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ManagerAgent_ServiceDesc, srv)
}

func _ManagerAgent_Channel_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ManagerAgentServer).Channel(&grpc.GenericServerStream[AgentMessage, LeaderMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ManagerAgent_ChannelServer = grpc.BidiStreamingServer[AgentMessage, LeaderMessage]

func _ManagerAgent_DownloadFile_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(DownloadRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ManagerAgentServer).DownloadFile(m, &grpc.GenericServerStream[DownloadRequest, FileChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ManagerAgent_DownloadFileServer = grpc.ServerStreamingServer[FileChunk]

func _ManagerAgent_UploadFile_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ManagerAgentServer).UploadFile(&grpc.GenericServerStream[UploadChunk, UploadResult]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ManagerAgent_UploadFileServer = grpc.ClientStreamingServer[UploadChunk, UploadResult]

// ManagerAgent_ServiceDesc is the grpc.ServiceDesc for ManagerAgent service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ManagerAgent_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "bpm.v1.ManagerAgent",
	HandlerType: (*ManagerAgentServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Channel",
			Handler:       _ManagerAgent_Channel_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "DownloadFile",
			Handler:       _ManagerAgent_DownloadFile_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "UploadFile",
			Handler:       _ManagerAgent_UploadFile_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "manager.proto",
}
