package config

import (
	"crypto/rand"
	"encoding/hex"
	"errors"
	"fmt"
	"io/fs"
	"log/slog"
	"os"
	"path/filepath"
	"strings"

	"github.com/joho/godotenv"
)

// generatedEnvFilename is written into DataDir on first leader boot to persist
// auto-generated secrets so subsequent reboots are deterministic.
const generatedEnvFilename = ".env.generated"

// EnsureLeaderSecrets — called only when Role()==Leader. If any required leader
// secret is missing in env, generate it, persist to ${DataDir}/.env.generated,
// and re-export to process env so the rest of Load() picks it up.
//
// This is split from Load() so it can be skipped for tests / agents.
// Safe to call multiple times.
func EnsureLeaderSecrets(dataDir string) error {
	if err := os.MkdirAll(dataDir, 0o700); err != nil {
		return fmt.Errorf("mkdir data dir: %w", err)
	}

	generatedPath := filepath.Join(dataDir, generatedEnvFilename)

	// Load previously generated values back into env (no overwrite — existing
	// env wins, so the operator can override a generated value by exporting it).
	if _, err := os.Stat(generatedPath); err == nil {
		if err := godotenv.Load(generatedPath); err != nil {
			slog.Warn("could not load generated env", "path", generatedPath, "err", err)
		}
	} else if !errors.Is(err, fs.ErrNotExist) {
		return fmt.Errorf("stat generated env: %w", err)
	}

	// Check which secrets are still missing AFTER loading .env.generated.
	required := map[string]int{
		"BPM_AGENT_TOKEN": 32, // 32 bytes → hex 64 chars
		"BPM_SECRETS_KEY": 32, // 32 bytes → AES-256-GCM key
		"BPM_TOTP_KEY":    32, // 32 bytes → AES-256-GCM key
	}

	missing := make(map[string]string)
	for key, n := range required {
		if os.Getenv(key) == "" {
			val, err := randomHex(n)
			if err != nil {
				return fmt.Errorf("random %s: %w", key, err)
			}
			missing[key] = val
			_ = os.Setenv(key, val) // make available to the current process
		}
	}

	if len(missing) == 0 {
		return nil
	}

	// Append to .env.generated. Use append-or-create so we never destroy
	// previously-written secrets if the file partially exists.
	f, err := os.OpenFile(generatedPath, os.O_CREATE|os.O_WRONLY|os.O_APPEND, 0o600)
	if err != nil {
		return fmt.Errorf("open generated env: %w", err)
	}
	defer f.Close()

	if info, statErr := f.Stat(); statErr == nil && info.Size() == 0 {
		header := "# Auto-generated by labextend on first leader boot.\n" +
			"# Do NOT commit. Backup separately — losing these means lost sessions\n" +
			"# and decrypted secrets.\n\n"
		if _, err := f.WriteString(header); err != nil {
			return fmt.Errorf("write header: %w", err)
		}
	}

	for k, v := range missing {
		line := fmt.Sprintf("%s=%s\n", k, v)
		if _, err := f.WriteString(line); err != nil {
			return fmt.Errorf("write %s: %w", k, err)
		}
		slog.Warn("auto-generated leader secret — persisted",
			"key", k, "file", generatedPath)
	}

	return nil
}

func randomHex(nBytes int) (string, error) {
	b := make([]byte, nBytes)
	if _, err := rand.Read(b); err != nil {
		return "", err
	}
	return hex.EncodeToString(b), nil
}

// stripQuotes is a small helper used elsewhere when reading env-like sources.
func stripQuotes(s string) string {
	s = strings.TrimSpace(s)
	if len(s) >= 2 && (s[0] == '"' || s[0] == '\'') && s[len(s)-1] == s[0] {
		return s[1 : len(s)-1]
	}
	return s
}

var _ = stripQuotes // reserved for future use
